### ISSUE TITLE
[ADD] 초기 닉네임 설정 화면 구성

### ISSUE THREAD

**Issue by glitterer** [AppleStop/AppleStop-iOS#11]
## 💡 Issue
닉네임 설정창 구성

## 📝  todo
- [ ] 닉네임 설명 버튼
- [ ] 닉네임 입력창
- [ ] 닉네임 입력창 누르면 커서 + Bottom-up 키패드
- [ ] 닉네임 설정하기 버튼
