### ISSUE TITLE
[FEAT] 새로운 캐릭터 추가 기능 구현

### ISSUE THREAD

**Issue by YoonAh-dev** [AppleStop/AppleStop-iOS#24]
## 💡 Issue

새로운 캐릭터를 추가하는 기능을 구현합니다.

## 📝  todo
- [x] 레벨 5, 10, 15 ... 가 됐을 때 lock이 풀리는 기능
- [x] 캐릭터 가져오기 버튼 구현
- [x] 캐릭터 가져오기 버튼을 누르는 부분 구현
- [x] 캐릭터 새로 추가하기 구현
