### ISSUE TITLE
[FEAT] 캐릭터 팝업과 캐릭터 창 연결

### ISSUE THREAD

**Issue by YoonAh-dev** [AppleStop/AppleStop-iOS#33]
## 💡 Issue

캐릭터 창을 누르면 캐릭터 팝업이 뜨도록 구현합니다.

## 📝  todo
- [x] 캐릭터 창 누르기 구현
- [x] 캐릭터 팝업 연결 구현
- [x] 변경을 누르면 대표 캐릭터 변경
